name: Makefile CI

on:
  push:
    branches: [ "tcc4tcl" ]
  pull_request:
    branches: [ "tcc4tcl" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install libsqlite3-dev libhiredis-dev

    - name: configure
      run: ./configure --maintainer --allext --disable-docs  LDFLAGS="-Wl,-rpath=. -L. -ltcc" "CFLAGS= -s -O2"  --with-ext=tcc

    - name: Build
      run: make
      
    - name: Run check
      run: make test

      
